trigger:
  branches:
    include:
      - main

stages:
  - stage: Build
    displayName: 'Building the Artifact'
    jobs:
      - job: BuildingArtifact
        displayName: 'Buid Artifact'
        pool:
          vmImage: 'windows-latest'
        steps:
          - template: templates/ci-pipeline.yml
            parameters:
              RunbookName: 'Automation_runbook_stg_to_dev.ps1'
              RunbookFolder: 'runbook'
              ArtifactName: 'AzAutArtifcat'
